import type { ComponentType, SVGProps } from "react";
import {
  ReactIcon,
  NextIcon,
  NodeIcon,
  GraphQLIcon,
  TailwindIcon,
  TypescriptIcon,
  JavascriptIcon,
  HtmlIcon,
  CssIcon,
  GithubIcon,
  GitIcon,
  ReactQueryIcon,
  ReduxIcon,
  ExpoIcon,
  SupabaseIcon,
  NeonIcon,
  RedisIcon,
  DrizzleIcon,
  MySQLIcon,
  MongoDBIcon,
  Clerk,
  Sanity,
  Appwrite,
  Prisma,
  Jest,
  Link,
  Resend,
  Stripe,
  Shadcn,
} from "@/components/icons";

const techIcons: Record<string, ComponentType<SVGProps<SVGSVGElement>>> = {
  react: ReactIcon,
  next: NextIcon,
  tailwind: TailwindIcon,
  typescript: TypescriptIcon,
  javascript: JavascriptIcon,
  html: HtmlIcon,
  css: CssIcon,
  git: GitIcon,
  github: GithubIcon,
  node: NodeIcon,
  graphql: GraphQLIcon,
  redux: ReduxIcon,
  reactquery: ReactQueryIcon,
  expo: ExpoIcon,
  supabase: SupabaseIcon,
  neon: NeonIcon,
  redis: RedisIcon,
  drizzle: DrizzleIcon,
  mysql: MySQLIcon,
  mongodb: MongoDBIcon,
  clerk: Clerk,
  sanity: Sanity,
  appwrite: Appwrite,
  prisma: Prisma,
  jest: Jest,
  link: Link,
  resend: Resend,
  stripe: Stripe,
  shadcn: Shadcn,
};

export function getSvg(
  iconName: string
): ComponentType<SVGProps<SVGSVGElement>> | undefined {
  return techIcons[iconName as keyof typeof techIcons];
}
