// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about_me: dynamic(() => import("./AboutMe")),
  blog: dynamic(() => import("./Blog")),
  contact: dynamic(() => import("./Contact")),
  experience: dynamic(() => import("./Experience")),
  footer: dynamic(() => import("./Footer")),
  hero: dynamic(() => import("./Hero")),
  navbar: dynamic(() => import("./Navbar")),
  projects: dynamic(() => import("./Projects")),
  services: dynamic(() => import("./Services")),
  testimonials: dynamic(() => import("./Testimonials")),
};
